#!/bin/sh
# $Id: syncsite,v 1.1 2004/11/12 01:03:16 mthuurne Exp $
#
# Logs into SourceForge shell using SSH and updates C-BIOS web site from CVS.
# If you have keypair authentication in place, everything is automatic.

SFUSER=`sed -e "s/^.*:\([^:@]*\)@cbios.cvs.*\$/\\1/" CVS/Root`
ssh $SFUSER@shell.sourceforge.net \
	"cd /home/groups/c/cb/cbios/htdocs ; cvs update -d"
